version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: peernetics-app
    restart: unless-stopped
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html
      - ./docker/php/php.ini:/usr/local/etc/php/conf.d/custom.ini
      - ./docker/supervisor/supervisord.conf:/etc/supervisor/conf.d/supervisord.conf
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./docker/entrypoint.sh:/usr/local/bin/entrypoint.sh
    ports:
      - "8000:80"  # Nginx will serve the app on port 80 inside the container
      - "8080:8080" 
    environment:
      - DB_CONNECTION=mysql
      - DB_HOST=db  # Reference to the MySQL container
      - DB_PORT=3306
      - DB_DATABASE=peernetics
      - DB_USERNAME=root
      - DB_PASSWORD=peernetics@2025  # Set your MySQL root password or a different user here
    depends_on:
      - db
    networks:
      - peernetics-network

  db:
    image: mariadb:10.5
    container_name: peernetics-db
    environment:
      MYSQL_ROOT_PASSWORD: peernetics@2025  # Same password as above
      MYSQL_DATABASE: peernetics
      MYSQL_USER: peerneticsuser
      MYSQL_PASSWORD: peerneticspass
    ports:
      - "3306:3306"
    volumes:
        - dbdata:/var/lib/mysql
        - ./peernetics_com.sql:/docker-entrypoint-initdb.d/peernetics_com.sql  # Mount SQL file directly
    restart: always
    networks:
      - peernetics-network
    
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    networks:
      - peernetics-network
    depends_on:
      - db
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: peernetics@2025
      UPLOAD_LIMIT: 300M
    ports:
      - "8181:80"
    restart: always

volumes:
  dbdata:

networks:
  peernetics-network:
    driver: bridge
